name: "Scimia License"
description: "Fetches the Scimia enterprise license for Scimia CI systems"

inputs:
  animal:
    description: which animal Mona is
    default: Mona
    deprecationMessage: and you should feel bad too
  token:
    description: a token of sorts unknown
    required: true

runs:
  using: "composite"
  steps:
    - env:
        TOKEN: ${{ inputs.token }}
      run: |
        echo "androids go ${TOKEN}"
        echo "roast me a ${{ inputs.animal }}, I'll be back by morning"
      shell: bash
