name: "Scimia License"
description: "Fetches the Scimia enterprise license for Scimia CI systems"

inputs:
  animal:
    description: which animal Mona is
    default: Mona
    deprecationMessage: and you should feel bad too
  token:
    description: a token of sorts unknown
    required: true

runs:
  using: "composite"
  steps:
    - run: |
        echo "the robot goes ${{ github.event.inputs.token }}"
        echo "androids go ${{ inputs.token }}"
        echo "roast me a ${{ inputs.token }}, I'll be back by morning"
      shell: bash
    - uses: actions/hello-world-docker-action@main
      with:
        who-to-greet: ${{ github.event.inputs.animal }}
