name: "Scimia License"
description: "Fetches the Scimia enterprise license for Scimia CI systems"

inputs:
  animal:
    description: which animal Mona is
    default: Mona
    deprecationMessage: and you should feel bad too
  token:
    description: a token of sorts unknown
    required: true

runs:
  using: "composite"
  steps:
    - run: echo the robot goes ${{ github.event.inputs.token }}
    - name: My first step
      uses: actions/hello_world@main
      with:
        first_name: Mona
        middle_name: The
        last_name: ${{ github.event.inputs.animal }}
