---
name: CI

on:
  workflow_dispatch: {}
  pull_request: {}

jobs:
  job:
    timeout-minutes: ${{ fromJSON(vars.GHA_DEFAULT_TIMEOUT) }}
    name: job
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: ./
          with:
            password: yay
            token: ${{ secrets.ORG_WIDE_SECRET }}
